### ISSUE TITLE
Finetuning the TTS model

### ISSUE THREAD

**Issue by sameearif** [facebookresearch/seamless_communication#111]
Is there a way to train the TTS for a single language on a custom dataset?

**Comment by cndn** [comment]
If you mean the vocoder to synthesize discrete units to audio, you could use this pipeline to get (audio, unit) pairs https://github.com/facebookresearch/seamless_communication/tree/main/scripts/m4t/audio_to_units, and then use https://github.com/facebookresearch/speech-resynthesis to train a Unit-HifiGAN vocoder, same as what we use for training 36 langauge vocoder.

**Comment by swanhtet1992** [comment]
@cndn Hello,

I am currently working on training a new vocoder to support an additional audio target language. Is it even possible for an individual with limited resources? 😅

I have run the finetuning scripts for M4T before and prepared the dataset for finetuning. During that phase, I noticed that we have (audio, unit) pairs ready. I also noticed that audio files are already 16 kHz too. I would like to know if I can use these pairs? Since the dataset preparation for finetuning step only produced a handful of data, I am not sure if it would be enough for training new language vocoder.

I checked https://github.com/facebookresearch/speech-resynthesis too, there are different dataset formats mentioned for training. Do I still need to follow https://github.com/facebookresearch/speech-resynthesis#preprocessing-new-datasets if I were to use the (audio, unit) pair produced by the finetuning step?

I am curious to know which format is used for the 36 language vocoder. 

I would appreciate any guidance on how to proceed with this.

Thank you.

**Comment by kzmaker** [comment]
> If you mean the vocoder to synthesize discrete units to audio, you could use this pipeline to get (audio, unit) pairs https://github.com/facebookresearch/seamless_communication/tree/main/scripts/m4t/audio_to_units, and then use https://github.com/facebookresearch/speech-resynthesis to train a Unit-HifiGAN vocoder, same as what we use for training 36 langauge vocoder.↳
Are there any specific tutorials?

**Comment by rhnaxifg4y** [comment]
@kzmaker any luck here?
