### ISSUE TITLE
Where can I find the source code for SeamlessWM?

### ISSUE THREAD

**Issue by systemdevart** [facebookresearch/seamless_communication#309]
Hi, the original paper mentions SeamlessWM, but I couldn't find it in the source code and can't get if it is now applied after the main Unity2 generation pipeline or not, and how can I use the actual classifier?

**Comment by Mortimerp9** [comment]
The watermarking is currently applied as part of the generation pipeline.

We are not yet releasing the classifier but keep an eye out for the upcoming paper about SeamlessWM.

**Comment by systemdevart** [comment]
@Mortimerp9 Could you please point out the part of the code where it is applied? I couldn't find any details.

**Comment by antoine-tran** [comment]
HI @systemdevart , we made a decision to integrate the SeamlessWM very deep into the whole architecture and it was not easy to de-couple the watermarking from the other components. The reason is that with the current solution of watermarking, if one can remove it from the vocoder, our voice generation pipeline can be used for other purposes that might not follow our AI responsibility commitment (i.e. generating voices of popular figures with unwanted statements).

That being said, we understand it is not completely satisfactory for the open-source community , and we are working on the next solution of SeamlessWM as @Mortimerp9 , where the open-sourcing is possible without risking of misuse. If you want to get informed about it, feel free to open another issue. Thanks !

**Comment by systemdevart** [comment]
@antoine-tran Thanks for the quick reply! I don't want to decouple the watermarking from Seamless; I want to now approach how you did it so I can reuse it in other TTS solutions.
And the paper doesn't state how you integrated it; it just presents the architecture

**Comment by antoine-tran** [comment]
@systemdevart The architecture presented in the paper is modified to integrate directly into the generator pipeline. Please watch out for a better solution to be released soon, where we are able to disclose this (both in the paper and in the code) without worrying about the implications.

**Comment by antoine-tran** [comment]
@systemdevart Getting back to your question, we have just released our watermarking today: https://github.com/facebookresearch/audioseal

Note that the weights and the architecture of the SeamlessWM is not the same as audioseal, as audioseal is right now targeting more research use cases. But I hope you can find it useful

**Comment by systemdevart** [comment]
@antoine-tran thanks for the response!
But in the audioseal paper, they use a separate model, and you pointed out that you somehow embedded that into a vocoder or acoustic model. How did you do that? The paper doesn't mention that.
