### ISSUE TITLE
Why only one previous word is used as input when predict the current word?

### ISSUE THREAD

**Issue by KeepSilentNow** [facebookresearch/seamless_communication#343]
I have a question and would greatly appreciate your help! In the [UnitY paper](https://arxiv.org/abs/2212.08055), the translation process is conducted in an autoregressive manner, where each prediction of the next word utilizes all previously predicted words. This is illustrated here:
![image](https://github.com/facebookresearch/fairseq2/assets/124227184/f19bc1b6-b818-4449-8962-9eca7fb03114)

However, in the actual implementation, why is only the previous word used as input each time? This is demonstrated here: [code](https://github.com/facebookresearch/fairseq2/blob/cbffdf0551058c32437088cb4dd60b6ade9b7f94/src/fairseq2/generation/beam_search.py#L662)
```
# fairseq2/generation/beam_search.py
 def _step(self) -> bool:
        # Generate the next step output.
        model_output = self._decode(self.seqs[:, self.step_nr - 1 : self.step_nr])  # here 

        self.state_bag.increment_step_nr()

        logits = model_output.logits
```

**Comment by avidale** [comment]
Hi! 
Here, only the previous ~~word~~ token is passed through the decoder, because all the previous tokens have already been processed by it before, so their representations can be reused. This is a standard technical trick, used in nearly all implementations of autoregressive decoding with transformers. 

Here is how it is implemented in fairseq2:
1. The method `_decode` that you mentioned above passes an additional argument `state_bag=self.state_bag` to the model: https://github.com/facebookresearch/fairseq2/blob/cbffdf0551058c32437088cb4dd60b6ade9b7f94/src/fairseq2/generation/beam_search.py#L1005
2. This argument is passed all the way down to the `forward` method of MultiheadAttention: https://github.com/facebookresearch/fairseq2/blob/cbffdf0551058c32437088cb4dd60b6ade9b7f94/src/fairseq2/nn/transformer/multihead_attention.py#L378
3. Within this method, the state_bag is unpacked to extract the keys and queries for all the previous tokens from it. Also, the key and value for the current token are appended to the state_bag, so that they can be reused at all subsequent generation steps: https://github.com/facebookresearch/fairseq2/blob/cbffdf0551058c32437088cb4dd60b6ade9b7f94/src/fairseq2/nn/transformer/multihead_attention.py#L398-L421

Hope this answers your question

**Comment by KeepSilentNow** [comment]
Understood. Thank you very much!
